### ISSUE TITLE
GetUserDataAsync throws a “Access Denied” error from connector client .

### ISSUE THREAD

**Issue by manikanta-dornala** [jeffhollan/BotFrameworkSample#2]

**Comment by jeffhollan** [comment]
Was going to check this out - what ended up being the issue?

**Comment by manikanta-dornala** [comment]
It wasn't actually an issue. Must say a mistake on my part. 
I was trying to run the bot from the emulator. So when the connector client made a request with the userId generated by the emulator, it could not find it as it was making a request to bot connector. 
The userId generated by the emulator was not registered by the bot connector, hence the error. It had me go nuts for a day, I don't know how I realized this in the end.
